<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXKHfXg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXKHfXg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSXKHfXg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSXKHfXg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSXKHfXg\App_KernelDevDebugContainer([
    'container.build_hash' => 'SXKHfXg',
    'container.build_id' => '8e1db64b',
    'container.build_time' => 1741008493,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSXKHfXg');
