<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2xi9q5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2xi9q5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ2xi9q5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ2xi9q5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ2xi9q5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z2xi9q5',
    'container.build_id' => '8ff7ece2',
    'container.build_time' => 1741101302,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2xi9q5');
